/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalystsRouteImport } from './routes/analysts'
import { Route as BooksRouteImport } from './routes/books'
import { Route as CardRouteImport } from './routes/card'
import { Route as EngineRouteImport } from './routes/engine'
import { Route as GamesRouteImport } from './routes/games'
import { Route as HelpRouteImport } from './routes/help'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LetterRouteImport } from './routes/letter'
import { Route as LogRouteImport } from './routes/log'
import { Route as ParlaysRouteImport } from './routes/parlays'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as WireRouteImport } from './routes/wire'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as LetterSlugRouteImport } from './routes/letter.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalystsRoute = AnalystsRouteImport.update({
  id: '/analysts',
  path: '/analysts',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineRoute = EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LetterRoute = LetterRouteImport.update({
  id: '/letter',
  path: '/letter',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const ParlaysRoute = ParlaysRouteImport.update({
  id: '/parlays',
  path: '/parlays',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const WireRoute = WireRouteImport.update({
  id: '/wire',
  path: '/wire',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LearnRoute,
} as any)
const LetterSlugRoute = LetterSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LetterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysts': typeof AnalystsRoute
  '/books': typeof BooksRoute
  '/card': typeof CardRoute
  '/engine': typeof EngineRoute
  '/games': typeof GamesRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/learn': typeof LearnRouteWithChildren
  '/legal': typeof LegalRoute
  '/letter': typeof LetterRouteWithChildren
  '/log': typeof LogRoute
  '/parlays': typeof ParlaysRoute
  '/sources': typeof SourcesRoute
  '/studio': typeof StudioRoute
  '/wire': typeof WireRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/letter/$slug': typeof LetterSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysts': typeof AnalystsRoute
  '/books': typeof BooksRoute
  '/card': typeof CardRoute
  '/engine': typeof EngineRoute
  '/games': typeof GamesRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/learn': typeof LearnRouteWithChildren
  '/legal': typeof LegalRoute
  '/letter': typeof LetterRouteWithChildren
  '/log': typeof LogRoute
  '/parlays': typeof ParlaysRoute
  '/sources': typeof SourcesRoute
  '/studio': typeof StudioRoute
  '/wire': typeof WireRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/letter/$slug': typeof LetterSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysts': typeof AnalystsRoute
  '/books': typeof BooksRoute
  '/card': typeof CardRoute
  '/engine': typeof EngineRoute
  '/games': typeof GamesRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/learn': typeof LearnRouteWithChildren
  '/legal': typeof LegalRoute
  '/letter': typeof LetterRouteWithChildren
  '/log': typeof LogRoute
  '/parlays': typeof ParlaysRoute
  '/sources': typeof SourcesRoute
  '/studio': typeof StudioRoute
  '/wire': typeof WireRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/letter/$slug': typeof LetterSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysts'
    | '/books'
    | '/card'
    | '/engine'
    | '/games'
    | '/help'
    | '/join'
    | '/learn'
    | '/legal'
    | '/letter'
    | '/log'
    | '/parlays'
    | '/sources'
    | '/studio'
    | '/wire'
    | '/learn/$slug'
    | '/letter/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysts'
    | '/books'
    | '/card'
    | '/engine'
    | '/games'
    | '/help'
    | '/join'
    | '/learn'
    | '/legal'
    | '/letter'
    | '/log'
    | '/parlays'
    | '/sources'
    | '/studio'
    | '/wire'
    | '/learn/$slug'
    | '/letter/$slug'
  id:
    | '__root__'
    | '/'
    | '/analysts'
    | '/books'
    | '/card'
    | '/engine'
    | '/games'
    | '/help'
    | '/join'
    | '/learn'
    | '/legal'
    | '/letter'
    | '/log'
    | '/parlays'
    | '/sources'
    | '/studio'
    | '/wire'
    | '/learn/$slug'
    | '/letter/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalystsRoute: typeof AnalystsRoute
  BooksRoute: typeof BooksRoute
  CardRoute: typeof CardRoute
  EngineRoute: typeof EngineRoute
  GamesRoute: typeof GamesRoute
  HelpRoute: typeof HelpRoute
  JoinRoute: typeof JoinRoute
  LearnRoute: typeof LearnRouteWithChildren
  LegalRoute: typeof LegalRoute
  LetterRoute: typeof LetterRouteWithChildren
  LogRoute: typeof LogRoute
  ParlaysRoute: typeof ParlaysRoute
  SourcesRoute: typeof SourcesRoute
  StudioRoute: typeof StudioRoute
  WireRoute: typeof WireRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysts': {
      id: '/analysts'
      path: '/analysts'
      fullPath: '/analysts'
      preLoaderRoute: typeof AnalystsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine': {
      id: '/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof EngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letter': {
      id: '/letter'
      path: '/letter'
      fullPath: '/letter'
      preLoaderRoute: typeof LetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parlays': {
      id: '/parlays'
      path: '/parlays'
      fullPath: '/parlays'
      preLoaderRoute: typeof ParlaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wire': {
      id: '/wire'
      path: '/wire'
      fullPath: '/wire'
      preLoaderRoute: typeof WireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof LearnRoute
    }
    '/letter/$slug': {
      id: '/letter/$slug'
      path: '/$slug'
      fullPath: '/letter/$slug'
      preLoaderRoute: typeof LetterSlugRouteImport
      parentRoute: typeof LetterRoute
    }
  }
}

interface LearnRouteChildren {
  LearnSlugRoute: typeof LearnSlugRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnSlugRoute: LearnSlugRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface LetterRouteChildren {
  LetterSlugRoute: typeof LetterSlugRoute
}

const LetterRouteChildren: LetterRouteChildren = {
  LetterSlugRoute: LetterSlugRoute,
}

const LetterRouteWithChildren =
  LetterRoute._addFileChildren(LetterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalystsRoute: AnalystsRoute,
  BooksRoute: BooksRoute,
  CardRoute: CardRoute,
  EngineRoute: EngineRoute,
  GamesRoute: GamesRoute,
  HelpRoute: HelpRoute,
  JoinRoute: JoinRoute,
  LearnRoute: LearnRouteWithChildren,
  LegalRoute: LegalRoute,
  LetterRoute: LetterRouteWithChildren,
  LogRoute: LogRoute,
  ParlaysRoute: ParlaysRoute,
  SourcesRoute: SourcesRoute,
  StudioRoute: StudioRoute,
  WireRoute: WireRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
